# testplan.ini — Test Plan Configuration.

# Follow this pattern for all the matrix combination for your test plan
#[test-job-name]
#  runs_on = oscii/on-prem test runner name. Ex: linux-mi325-1gpu-ossci-rocm-frac
#  artifact_group = artifact target group to therock installation. Ex: gfx94X-dcgpu, gfx950-dcgpu
#  tests_filters = test filter expression for pytest -k input. Ex: "ci.nightly and hw.gpu", "ci.nightly"


# test plan for MI300A targets
[linux-gfx94x-MI300A]
  runs_on = MI300A
  artifact_group = gfx94X-dcgpu
  gpu_arch = gfx942
  tests_filters = ci.nightly and hw.gpu
  target_available = true

# test plan for MI300A targets
[linux-gfx94x-MI308X]
  runs_on = MI308X
  artifact_group = gfx94X-dcgpu
  gpu_arch = gfx942
  tests_filters = ci.nightly and hw.gpu
  target_available = true

# test plan for MI325 targets
[linux-gfx94x-MI325]
  runs_on = linux-gfx942-1gpu-ossci-rocm
  artifact_group = gfx94X-dcgpu
  gpu_arch = gfx942
  tests_filters = ci.nightly and hw.gpu
  target_available = true
  extra_docker_args = --env-file /etc/podinfo/gha-gpu-isolation-settings

# test plan for MI355 targets
[linux-gfx950-MI355]
  runs_on = linux-mi355-1gpu-ossci-rocm
  artifact_group = gfx950-dcgpu
  gpu_arch = gfx950
  tests_filters = ci.nightly and hw.gpu
  target_available = true
  extra_docker_args = --env-file /etc/podinfo/gha-gpu-isolation-settings

# test plan for stix halo targets
[linux-gfx1151]
  runs_on = linux-gfx1151-gpu-rocm
  artifact_group = gfx1151
  gpu_arch = gfx1151
  tests_filters = ci.nightly and hw.gpu
  target_available = true
  extra_docker_args = --env-file /etc/podinfo/gha-gpu-isolation-settings


######### place holder for other targets ######

[linux-gfx94X-multigpu]
  runs_on = linux-mi325-8gpu-ossci-rocm
  artifact_group = gfx94X-dcgpu
  gpu_arch = gfx942
  tests_filters = hw.multigpu
  target_available = false

[linux-gfx110X]
  runs_on = linux-gfx110X-gpu-rocm
  artifact_group = gfx110X-all
  gpu_arch = gfx110X-all
  tests_filters = ci.nightly and hw.gpu
  target_available = false

[linux-gfx120X]
  runs_on = linux-gfx120X-gpu-rocm
  artifact_group = gfx120X-all
  gpu_arch = gfx120X-all
  tests_filters = ci.nightly and hw.gpu
  target_available = false

[linux-gfx90a]
  runs_on = linux-gfx90a-gpu-rocm
  artifact_group = gfx90a
  gpu_arch = gfx90a
  tests_filters = ci.nightly and hw.gpu
  target_available = false

[linux-gfx103X]
  runs_on = linux-gfx1030-gpu-rocm
  artifact_group = gfx103X-all
  gpu_arch = gfx103X-all
  tests_filters = ci.nightly and hw.gpu
  target_available = false

[linux-gfx1150]
  runs_on = linux-gfx1150-gpu-rocm
  artifact_group = gfx1150
  gpu_arch = gfx1150
  tests_filters = ci.nightly and hw.gpu
  target_available = false

[linux-gfx1153]
  runs_on = linux-gfx1153-gpu-rocm
  artifact_group = gfx1153
  gpu_arch = gfx1153
  tests_filters = ci.nightly and hw.gpu
  target_available = false
