# testplan.ini — Test Plan Configuration.

# Follow this pattern for all the matrix combination for your test plan
#[test-job-name]
#  runs_on = oscii/on-prem test runner name. Ex: linux-mi325-1gpu-ossci-rocm-frac
#  artifact_group = artifact target group to therock installation. Ex: gfx94X-dcgpu, gfx950-dcgpu
#  tests_filters = test filter expression for pytest -k input. Ex: "ci.nightly and hw.gpu", "ci.nightly"


# test plan for MI325 targets
[linux-gfx94x]
  runs_on = linux-gfx942-1gpu-ossci-rocm
  artifact_group = gfx94X-dcgpu
  gpu_arch = gfx942
  tests_filters = "ci.nightly and hw.gpu"


# test plan for MI355 targets
[linux-gfx950]
  runs_on = linux-mi355-1gpu-ossci-rocm
  artifact_group = gfx950-dcgpu
  gpu_arch = gfx950
  tests_filters = "ci.nightly and hw.gpu"


## test plan for multi GPU MI325 targets
#[linux-gfx94X-multigpu]
#  runs_on = linux-mi325-8gpu-ossci-rocm
#  artifact_group = gfx94X-dcgpu
#  tests_filters = 'multigpu'
